### ISSUE TITLE
关于方法调用的重要Bug Report

### ISSUE THREAD

**Issue by HotspringDev** [Jinsens/Jinsen#3]
今天正在对Jinsen-Z8进行code review的时候偶然发现了这一问题
![Screenshot_2023-12-02-16-40-19-532_bin.mt.plus.jpg](https://github.com/Jinsens/Jinsen/assets/78401087/23f917d1-53fc-4f00-a8e3-7a00fda51d1c)
如图所示，在刷入模块时 模块会把一个signal写入到/data/jinsen/config.conf中，若按下音量上则启用第三方调度方案
![Screenshot_2023-12-02-16-40-26-298_bin.mt.plus.jpg](https://github.com/Jinsens/Jinsen/assets/78401087/d9cff790-ce04-4f27-8f1e-712b6b7d8ca0)
然而在service.sh中，若从上述conf文件读到的是on的话 则启用了官方调度方案（？？）
official方法里执行的全部都是enable joyose的命令，这应该是一个巨大的逻辑错误.

**Comment by Jinsens** [comment]
下个版本修复，等明天或者后天
