### ISSUE TITLE
红米note12turbo充电锁功率

### ISSUE THREAD

**Issue by byf3332** [Jinsens/Jinsen#5]
如题，z9r版本下我的充电功率被锁到15w，z9a锁5w，z3锁25w
目前只发现CI3不会锁功率，但CI3和第三方调度并不是很合得来
尝试给后面的版本替换CI3的config，效果并不好
关机充电似乎不会被锁功率，怀疑是温控问题
系统版本14.0.19

**Comment by Jinsens** [comment]
换Z9e

**Comment by byf3332** [comment]
看样子是修好了，有问题我再反馈，感谢
先close了👀👍
